name: container
on: [push]

jobs:
  docker-job:
    runs-on: ubuntu-latest
    container:
      image: node:13.5.0-alpine3.10
    steps:
    - name: log node version
      runs: |
        node -v
        cat /etc/os-release